#!/bin/bash
cp Dockerfile arch_linux/

if ! [ -z $1 ]
then
	NAME=$1
	echo $NAME
else
	echo "Please enter a container name"
	exit 1
fi


USER=$(whoami)

USR=$NAME"_usr"
LIB=$NAME"_lib"
CONTAINER_HOME=$NAME"_home"
ETC=$NAME"_etc"


sudo docker volume create $USR 
sudo docker volume create $LIB
sudo docker volume create $CONTAINER_HOME
sudo docker volume create $ETC

sudo chmod 777 /var/lib/docker
sudo chmod 777 /var/lib/docker/volumes

sudo docker build --build-arg USER=$USER -t jacobmealey/$NAME:latest arch-linux/

sudo ln -s /var/lib/docker/volumes/$CONTAINER_HOME/_data/ arch-linux/home
sudo ln -s /var/lib/docker/volumes/$USR/_data/ arch-linux/usr
sudo ln -s /var/lib/docker/volumes/$ETC/_data/ arch-linux/etc
sudo ln -s /var/lib/docker/volumes/$LIB/_data/ arch-linux/lib

sudo rm -rf arch-linux/*/


