#!/bin/bash

USER=$(whoami)

USR="arch_usr"
LIB="arch_lib"
CONTAINER_HOME="arch_home"
ETC="arch_etc"


sudo docker volume create $USR 
sudo docker volume create $LIB
sudo docker volume create $CONTAINER_HOME
sudo docker volume create $ETC

sudo chmod 777 /var/lib/docker
sudo chmod 777 /var/lib/docker/volumes

sudo docker build --build-arg USER=$USER -t jacobmealey/kin:latest arch-linux/
sudo docker run jacobmealey/kin:latest

sudo ln -s /var/lib/docker/volumes/$CONTAINER_HOME/_data/ arch-linux/home
sudo ln -s /var/lib/docker/volumes/$USR/_data/ arch-linux/usr
sudo ln -s /var/lib/docker/volumes/$ETC/_data/ arch-linux/etc
sudo ln -s /var/lib/docker/volumes/$LIB/_data/ arch-linux/lib

sudo rm -rf arch-linux/*/


