#!/bin/bash
USR="arch_usr"
LIB="arch_lib"
CONTAINER_HOME="arch_home"
ETC="arch_etc"

sudo docker run -it \
	-e DISPLAY=$DISPLAY\
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	--mount source=$USR,target=/usr\
	--mount source=$ETC,target=/etc\
	--mount source=$LIB,target=/lib\
	--mount source=$CONTAINER_HOME,target=/home\
	jacobmealey/kin:latest
	




